# Issue and PR Labels
# Format: each label has both regex patterns for content matching (for issues)
# and path patterns (for PRs)

'🐞 bug':
  title: '(?i).*\b(bug|error|failure|crash|broken|not working|doesn''t work|isn''t working|problem|issue|defect|fault)\b.*'
  paths:
    - '**/tests/**/*'
    - '**/src/**/*'
    - '!docs/*'
    - '!*.md'

'📝 documentation':
  title: '(?i).*\b(docs?|documentation|readme|wiki|guide|tutorial|example)\b.*'
  paths:
    - 'docs/**/*'
    - '**/*.md'
    - '**/README.md'
    - '**/CONTRIBUTING.md'

'❌ duplicate':
  title: '(?i).*\b(duplicat(e|ed)|already exists|similar to|same as)\b.*'

'🚀 enhancement':
  title: '(?i).*\b(enhancement|feature request|new feature|improvement|suggest|proposal|idea)\b.*'
  paths:
    - '**/feature/**/*'
    - '**/enhancement/**/*'

'🤝 good first issue':
  title: '(?i).*\b(good first issue|beginner friendly|easy|starter|newcomer|first timer)\b.*'
  paths:
    - 'examples/**/*'
    - 'docs/**/*'

'🏗️ help wanted':
  title: '(?i).*\b(help wanted|need help|assistance needed|looking for help|support needed)\b.*'

'🚧 in progress':
  title: '(?i).*\b(in progress|wip|working on|ongoing|under development|implementing)\b.*'
  paths:
    - '**/wip/**/*'

'⚠️ invalid':
  title: '(?i).*\b(invalid|incorrect|wrong|mistake|not right|inappropriate|malformed)\b.*'

'🔄 needs testing':
  title: '(?i).*\b(needs? testing|test required|verification needed|qa|quality assurance|test coverage)\b.*'
  paths:
    - '**/tests/**/*'
    - '**/__tests__/**/*'
    - '**/*.test.*'
    - '**/*.spec.*'

'❓ question':
  title: '(?i).*(\?|question|how to|what is|when|where|why|who|how do|can someone|is there|are there).*'
  paths:
    - 'docs/**/*'
    - '.github/ISSUE_TEMPLATE/question.md'

'🛡️ security':
  title: '(?i).*\b(security|vulnerability|exploit|cve|sensitive|auth|authentication|authorization|permission)\b.*'
  paths:
    - '**/security/**/*'
    - '**/auth/**/*'
    - '**/authentication/**/*'

'⏳ waiting for feedback':
  title: '(?i).*\b(waiting for|awaiting|pending|need feedback|need response|need clarification|need more info)\b.*'

'🚫 won''t fix':
  title: '(?i).*\b(wont fix|won''t fix|will not fix|not fixing|declined|rejected|intended behavior)\b.*'