#!/usr/bin/env python3
"""Export the model-card rubric as JSON, so a second runtime cannot drift from it.

The browser scorer in the GOPAL playground has to produce the same number as
`aicertify score-card`, or the published figures stop meaning anything. Two
hand-maintained copies of a rubric diverge; this one is generated from the
Python that defines it, and CI fails if the committed copy is stale.

Five things decide the score and all five are exported:

* which subsections each of the nine sections requires
* which model-card headings map onto each subsection
* the weight of each section in the overall completeness score
* the character counts separating minimal, partial and comprehensive content
* the score attached to each of those quality levels

Usage:
    export_model_card_rubric.py            rewrite the JSON
    export_model_card_rubric.py --check    fail if it is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from aicertify.adapters.huggingface_adapter import SUBSECTION_SOURCES  # noqa: E402
from aicertify.evaluators.documentation.model_card_evaluator import (  # noqa: E402
    ModelCardEvaluator,
)

TARGET = REPO / "aicertify" / "adapters" / "model_card_rubric.json"
FIXTURES = REPO / "aicertify" / "adapters" / "model_card_parity_fixtures.json"


# Cards written here rather than copied from the Hub, so nothing redistributes
# someone else's documentation. Between them they exercise the current
# template, the older convention most high-download repositories still use,
# prose that lives only in subsections, and a card with nothing in it.
_FIXTURE_CARDS = {
    "modern-template": """---
license: apache-2.0
datasets:
  - squad
pipeline_tag: text-classification
---

# Fixture Modern

## Model Details

A transformer classifier written as a fixture, with enough prose to sit above
the minimal content threshold but below the comprehensive one, so that a
scorer which mixes up the two bands is caught here rather than in production.

## Uses

### Direct Use

Classifying short English passages where a person reviews the result before
anything happens because of it.

### Out-of-Scope Use

Not for medical, legal, hiring or credit decisions.

## Bias, Risks, and Limitations

Trained on web text and carries its biases, with degraded performance on
under-represented dialects.

## Training Details

### Training Data

SQuAD, deduplicated and filtered for length.

### Preprocessing

Lowercased and tokenised with WordPiece.

## Evaluation

Evaluated on GLUE, validation split.

## Recommendations

Re-evaluate on your own data before deploying into a new domain.
""",
    "legacy-template": """---
license: mit
---

# Fixture Legacy

## Model description

The older heading convention, still carried by a great many popular
repositories that were written before the current template existed.

## Intended uses & limitations

Masked language modelling and downstream fine-tuning. Not for generating
factual text.

## Limitations and bias

The training data contains unfiltered internet content and the model
reproduces stereotypes present in it.

## Training data

BookCorpus and English Wikipedia.

## Training procedure

### Preprocessing

Lowercased, WordPiece, 30,000 token vocabulary.
""",
    "headings-only": """# Fixture Sparse

## Uses

Short.

## Training
""",
    "empty": """# Fixture Empty
""",
}


def build() -> dict:
    evaluator = ModelCardEvaluator()
    sections = {
        section_id: {
            "name": info["name"],
            "weight": info["weight"],
            "subsections": list(info["subsections"]),
        }
        for section_id, info in evaluator.REQUIRED_SECTIONS.items()
    }
    return {
        "_comment": (
            "Generated by scripts/export_model_card_rubric.py. Do not edit by "
            "hand. The browser scorer reads this so it cannot drift from the "
            "Python that produced it."
        ),
        "version": 1,
        "sections": sections,
        "heading_sources": {
            section: {sub: list(aliases) for sub, aliases in subs.items()}
            for section, subs in SUBSECTION_SOURCES.items()
        },
        "quality_levels": {
            level: info["score"] for level, info in evaluator.QUALITY_LEVELS.items()
        },
        "content_thresholds": dict(evaluator.content_quality_thresholds),
        "compliance_threshold": evaluator.compliance_threshold,
    }


def build_fixtures() -> dict:
    """Cards with the score Python gives them, for a second runtime to match.

    The browser scorer has to agree with this one or the published figures mean
    nothing. Agreement is asserted against these rather than against a live
    Hub fetch, so the check is deterministic and needs no network. The cards
    are written here rather than copied from the Hub, so there is no question
    about redistributing someone else's documentation.
    """
    from aicertify.adapters import from_model_card
    from aicertify.evaluators.documentation import ModelCardEvaluator

    evaluator = ModelCardEvaluator()
    cases = []
    for name, card in _FIXTURE_CARDS.items():
        fragment = from_model_card(card)
        result = evaluator.evaluate(fragment.get("documentation", {}))
        emitted = (result.details or {}).get("metrics", {}).get("model_card", {})
        cases.append(
            {
                "name": name,
                "card": card,
                "expected": {
                    "completeness": round(emitted.get("completeness", 0.0), 10),
                    "quality": round(emitted.get("quality", 0.0), 10),
                    "section_scores": {
                        k: round(v, 10)
                        for k, v in sorted(
                            (result.details or {}).get("section_scores", {}).items()
                        )
                    },
                },
            }
        )
    return {
        "_comment": (
            "Generated by scripts/export_model_card_rubric.py. Any second "
            "implementation of the rubric must reproduce these scores exactly."
        ),
        "version": 1,
        "cases": cases,
    }


def main() -> int:
    rendered = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    fixtures = json.dumps(build_fixtures(), indent=2, sort_keys=True) + "\n"
    check = "--check" in sys.argv

    if check:
        if not TARGET.exists():
            print(f"{TARGET} is missing; run {Path(__file__).name}", file=sys.stderr)
            return 1
        stale = []
        if TARGET.read_text() != rendered:
            stale.append(TARGET)
        if not FIXTURES.exists() or FIXTURES.read_text() != fixtures:
            stale.append(FIXTURES)
        if stale:
            names = ", ".join(str(f.relative_to(REPO)) for f in stale)
            print(
                f"Out of date: {names}\n"
                f"The rubric changed in Python and the browser scorer still "
                f"reads the old one.\n"
                f"Run scripts/{Path(__file__).name} and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(REPO)} and its parity fixtures are up to date.")
        return 0

    TARGET.write_text(rendered)
    FIXTURES.write_text(fixtures)
    print(f"Wrote {TARGET.relative_to(REPO)}")
    print(f"Wrote {FIXTURES.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
