name: AICertify CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  basic-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Updated to match project requirements

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install

      - name: Run Code Linting with Pre-commit
        run: |
          poetry run pre-commit run --all-files

      - name: Verify Package Installation
        run: |
          poetry run python -c "import aicertify; print(f'AICertify version: {aicertify.__version__}')"

      # Temporarily disabled until we have more reliable tests
      # - name: Run Basic Tests
      #   run: poetry run pytest tests/ -v
