name: AICertify CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run AI Policy Validation
        run: |
          python cli.py --category compliance/eu_ai_act --input examples/input_examples.json
