name: Auto Label Issues & PRs

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened, ready_for_review, converted_to_draft]

  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      # Label PRs using actions/labeler
      - name: Label PRs
        if: github.event_name == 'pull_request'
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

      # Label issues using issue-labeler
      - name: Label issues based on content
        if: github.event_name == 'issues'
        uses: github/issue-labeler@v3.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          include-title: 1

      # Add in-progress label for draft PRs
      - name: Add in-progress label for draft PRs
        if: |
          github.event_name == 'pull_request' && 
          github.event.pull_request.draft == true
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "🚧 in progress"

      # Remove in-progress when PR is ready for review
      - name: Remove in-progress label when ready for review
        if: |
          github.event_name == 'pull_request' && 
          github.event.action == 'ready_for_review'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "🚧 in progress"

      # Automatically add "in progress" label for draft PRs
      - name: Add in-progress label for draft PRs
        if: |
          github.event_name == 'pull_request' && 
          (github.event.action == 'opened' || github.event.action == 'converted_to_draft') && 
          github.event.pull_request.draft == true
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "🚧 in progress"

      # Add "waiting for feedback" when review requested
      - name: Add waiting-for-feedback label on review request
        if: |
          github.event_name == 'pull_request' && 
          github.event.action == 'review_requested'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "⏳ waiting for feedback"

      # Remove "waiting for feedback" when PR is updated
      - name: Remove waiting-for-feedback label on PR update
        if: |
          github.event_name == 'pull_request' && 
          github.event.action == 'synchronize'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "⏳ waiting for feedback"

      # Add "needs testing" when PR is ready for review
      - name: Add needs-testing label when PR is ready
        if: |
          github.event_name == 'pull_request' && 
          github.event.action == 'ready_for_review'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "🔄 needs testing"

      # Clean up labels when PR/issue is closed
      - name: Clean up status labels on close
        if: |
          (github.event_name == 'pull_request' || github.event_name == 'issues') && 
          github.event.action == 'closed'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            🚧 in progress
            ⏳ waiting for feedback
            🔄 needs testing
